version: "3.3"

services:
  flask:
    image: teamcitywasamistake/flask-mongo:latest
    ports:
      - "8080:8080"
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 2
networks:
  appnet:
    driver: overlay
    attachable: true
